version: '3.8'

services:
  api:
    build: .
    container_name: multilingual_rag_api
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./docs:/app/docs

  frontend:
    build: .
    container_name: multilingual_rag_frontend
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./docs:/app/docs
